# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170314_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
