# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
